from pathlib import Path
p=Path('/mnt/data/work/Gosper_Global_Design/script.js')
s=p.read_text()
s=s.replace("function teamObjects(comp){const dbAll=state.teams.filter(t=>!comp||t.competition===comp);if(dbAll.length)return dbAll.filter(t=>t.enabled!==false);return catalog.filter(t=>!comp||t.competition===comp);}","""function teamCompetitions(t){return Array.isArray(t.competitions)&&t.competitions.length?t.competitions:(t.competition?[t.competition]:[])}
function isCompActive(comp){const a=state.season?.activeCompetitions;return !Array.isArray(a)||!a.length||a.includes(comp)}
function teamObjects(comp){const source=state.teams.length?state.teams:catalog;return source.filter(t=>t.enabled!==false&&(!comp||teamCompetitions(t).includes(comp)))}
function activeTeams(comp){return teamObjects(comp).filter(t=>isCompActive(comp))}""")
s=s.replace("const comp=$('competition').value, query=q.toLowerCase();const teams=teamObjects(comp).filter(t=>t.name.toLowerCase().includes(query));", "const comp=$('competition').value, query=q.toLowerCase();const teams=activeTeams(comp).filter(t=>t.name.toLowerCase().includes(query));")
s=s.replace("function renderTeams(){const q=($('teamSearch')?.value||'').toLowerCase(),c=$('teamCompetition')?.value||'all';let ts=teamObjects().filter(t=>!q||t.name.toLowerCase().includes(q));if(c!=='all')ts=ts.filter(t=>t.competition===c);", "function renderTeams(){const q=($('teamSearch')?.value||'').toLowerCase(),c=$('teamCompetition')?.value||'all';let ts=teamObjects().filter(t=>!q||t.name.toLowerCase().includes(q));if(c!=='all')ts=ts.filter(t=>teamCompetitions(t).includes(c));")
s=s.replace("function renderDashboard(){const pl=table('Premier League');", "function renderDashboard(){const pl=table('Premier League');")
s=s.replace("function showCompetition(c){const teams=teamObjects(c);", "function showCompetition(c){const teams=activeTeams(c);")
# replace auth/admin block
start=s.index("// ---------- Admin ----------")
end=s.index("auth.onAuthStateChanged", start)
new=r'''// ---------- Admin ----------
$('adminLoginBtn')?.addEventListener('click',openAdminLogin);$('adminLoginBtn2')?.addEventListener('click',openAdminLogin);
function openAdminLogin(){
  const email=prompt('Admin email:'); if(!email)return;
  const password=prompt('Admin password:'); if(password===null)return;
  auth.signInWithEmailAndPassword(email.trim(),password).then(async()=>{state.admin=true;await loadData();go('admin');}).catch(e=>alert('Admin login failed. Check Firebase Authentication email/password.'));
}
async function adminSave(collection,id,data){
  const ref=db.collection(collection).doc(id||db.collection(collection).doc().id);
  await ref.set({...data,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});
  await loadData();
}
async function adminDelete(collection,id){if(!confirm('Delete this item?'))return;await db.collection(collection).doc(id).delete();await loadData();}
function renderAdmin(){
 const a=$('adminArea');
 if(!state.admin){a.innerHTML=`<div class="admin-lock"><div class="lock-icon">⚙</div><h2>Admin access required</h2><p>Sign in with your Firebase administrator account.</p><button class="primary" id="adminLoginBtn2">Sign in to Control Center</button></div>`;$('adminLoginBtn2').onclick=openAdminLogin;return;}
 a.innerHTML=`<div class="admin-shell"><div class="admin-nav"><button class="admin-tab active" data-admin-tab="overview">Overview</button><button class="admin-tab" data-admin-tab="competitions">Competitions</button><button class="admin-tab" data-admin-tab="teams">Teams</button><button class="admin-tab" data-admin-tab="fixtures">Fixtures</button><button class="admin-tab" data-admin-tab="results">Results</button><button class="admin-tab" data-admin-tab="promotion">Promotion / Relegation</button><button class="admin-tab" data-admin-tab="news">News</button><button class="admin-tab" data-admin-tab="hall">Hall of Fame</button><button class="admin-tab" data-admin-tab="season">Season</button><button class="ghost" id="adminSignOut">Sign out</button></div><div id="adminContent"></div></div>`;
 document.querySelectorAll('.admin-tab').forEach(b=>b.onclick=()=>adminTab(b.dataset.adminTab));$('adminSignOut').onclick=()=>auth.signOut().then(()=>{state.admin=false;renderAdmin();});adminTab('overview');
}
function adminTab(tab){
 document.querySelectorAll('.admin-tab').forEach(b=>b.classList.toggle('active',b.dataset.adminTab===tab));
 const c=$('adminContent');
 if(tab==='overview')adminOverview(c);if(tab==='competitions')adminCompetitions(c);if(tab==='teams')adminTeams(c);if(tab==='fixtures')adminFixtures(c);if(tab==='results')adminResults(c);if(tab==='promotion')adminPromotion(c);if(tab==='news')adminNews(c);if(tab==='hall')adminHall(c);if(tab==='season')adminSeason(c);
}
function adminOverview(c){
 const active=(state.season?.activeCompetitions||['Premier League','Championship','UCL']);
 c.innerHTML=`<div class="admin-grid"><div class="admin-stat"><b>${state.teams.length||catalog.length}</b><span>Clubs in system</span></div><div class="admin-stat"><b>${state.players.length}</b><span>Players</span></div><div class="admin-stat"><b>${state.fixtures.length}</b><span>Fixtures</span></div><div class="admin-stat"><b>${state.fixtures.filter(f=>score(f)).length}</b><span>Results entered</span></div></div><div class="admin-control-card"><div><p class="eyebrow">CURRENT SEASON</p><h2>${esc(state.season?.name||DEFAULT_SEASON)}</h2><p class="muted">Active competitions: ${active.map(esc).join(' • ')}</p></div><button class="primary" id="quickComp">Choose competitions</button></div><div class="admin-control-card"><div><p class="eyebrow">SEASON MOVEMENT</p><h2>Automatic promotion & relegation</h2><p class="muted">At season end: bottom 3 Premier League clubs move to Championship; top 3 Championship clubs move to Premier League.</p></div><button class="primary" id="quickMove">Open</button></div>`;
 $('quickComp').onclick=()=>adminTab('competitions');$('quickMove').onclick=()=>adminTab('promotion');
}
function adminCompetitions(c){
 const active=state.season?.activeCompetitions||['Premier League','Championship','UCL'];
 c.innerHTML=`<div class="admin-heading"><div><p class="eyebrow">COMPETITION CONTROL</p><h2>Choose what is running this Season</h2><p>Unaweza kuendesha PL, Championship, UCL au zote kwa pamoja.</p></div></div><div class="competition-control-grid">${['Premier League','Championship','UCL'].map(x=>`<label class="competition-toggle"><input type="checkbox" data-active-comp="${x}" ${active.includes(x)?'checked':''}><span class="toggle-copy"><b>${x}</b><small>${x==='UCL'?'Admin-selected clubs • Groups & Knockout':'League • Home & Away'}</small></span><strong>${active.includes(x)?'ACTIVE':'OFF'}</strong></label>`).join('')}</div><div class="admin-actions-row"><button class="primary" id="saveActiveComps">Save Competition Setup</button></div>`;
 $('saveActiveComps').onclick=async()=>{const active=[...document.querySelectorAll('[data-active-comp]:checked')].map(x=>x.dataset.activeComp);if(!active.length)return alert('Select at least one competition.');await adminSave('seasons',SEASON_ID,{activeCompetitions:active});alert('Competition setup saved.');adminTab('competitions');};
}
function adminTeams(c){
 const all=[...catalog,...state.teams.filter(t=>!catalog.some(x=>x.name===t.name))].reduce((m,t)=>m.set(t.name,{...t,...(state.teams.find(x=>x.name===t.name)||{})}),new Map());
 c.innerHTML=`<div class="admin-heading"><div><p class="eyebrow">CLUB CONTROL</p><h2>Teams & competition membership</h2><p>Club inaweza kuwa Premier League + UCL kwa wakati mmoja. Championship nayo inadhibitiwa hapa.</p></div><button class="primary" id="saveTeams">Save Team Setup</button></div><div class="admin-team-grid">${[...all.values()].map(t=>{const cs=teamCompetitions(t);return `<div class="admin-team-card"><div class="admin-team-main">${logo(t.name)}<div><b>${esc(t.name)}</b><small>${t.enabled===false?'Disabled':'Available'}</small></div></div><div class="comp-checks"><label><input type="checkbox" data-team-comp="Premier League" data-team-name="${esc(t.name)}" ${cs.includes('Premier League')?'checked':''}> PL</label><label><input type="checkbox" data-team-comp="Championship" data-team-name="${esc(t.name)}" ${cs.includes('Championship')?'checked':''}> CH</label><label><input type="checkbox" data-team-comp="UCL" data-team-name="${esc(t.name)}" ${cs.includes('UCL')?'checked':''}> UCL</label><label class="enable-check"><input type="checkbox" data-team-enabled="${esc(t.name)}" ${t.enabled!==false?'checked':''}> Available</label></div></div>`}).join('')}</div>`;
 $('saveTeams').onclick=async()=>{try{const batch=db.batch();const names=[...all.keys()];for(const name of names){const checks=[...document.querySelectorAll(`[data-team-name="${CSS.escape(name)}"]:checked`)].map(x=>x.dataset.teamComp);const enabled=document.querySelector(`[data-team-enabled="${CSS.escape(name)}"]`).checked;const old=[...all.values()].find(x=>x.name===name);const ref=db.collection('teams').doc(name.toLowerCase().replace(/[^a-z0-9]+/g,'-'));batch.set(ref,{name,competitions:checks,competition:checks[0]||old.competition||'Premier League',logo:old.logo||'',enabled,seasonId:SEASON_ID},{merge:true});}await batch.commit();await loadData();alert('Team setup saved.');adminTab('teams');}catch(e){console.error(e);alert('Could not save teams. Check Firestore Rules for admin writes.');}};
}
function adminFixtures(c){c.innerHTML=`<div class="admin-heading"><div><p class="eyebrow">FIXTURE ENGINE</p><h2>Fixtures</h2><p>Generate Home & Away for PL or Championship. UCL can be controlled separately.</p></div><div class="admin-actions"><select id="genComp"><option>Premier League</option><option>Championship</option></select><button class="primary" id="generateFixtures">Generate Home & Away</button></div></div><div class="form-grid admin-form"><select id="fxComp"><option>Premier League</option><option>Championship</option><option>UCL</option></select><input id="fxHome" placeholder="Home team"><input id="fxAway" placeholder="Away team"><input id="fxDate" type="date"><input id="fxRound" placeholder="Round / Matchday"><button class="primary" id="addFixture">Add Fixture</button></div><div class="admin-list">${state.fixtures.slice().sort((a,b)=>(dateObj(a.date)||0)-(dateObj(b.date)||0)).map(f=>fixtureHtml(f,true)).join('')||'<p class="muted">No fixtures yet.</p>'}</div>`;$('generateFixtures').onclick=()=>generateFixtures($('genComp').value);$('addFixture').onclick=async()=>{const id=db.collection('fixtures').doc().id;await adminSave('fixtures',id,{competition:$('fxComp').value,homeTeam:$('fxHome').value.trim(),awayTeam:$('fxAway').value.trim(),date:$('fxDate').value,round:$('fxRound').value||'Matchday',seasonId:SEASON_ID});adminTab('fixtures');};}
async function generateFixtures(comp){const ts=teamObjects(comp).map(t=>t.name);if(ts.length<2){alert('At least 2 teams are required.');return;}const existing=new Set(state.fixtures.filter(f=>compOf(f)===comp).map(f=>`${f.homeTeam||f.home}|${f.awayTeam||f.away}`));let arr=ts.slice();if(arr.length%2)arr.push(null);const n=arr.length,rounds=n-1,half=n/2,batch=db.batch();let count=0;for(let r=0;r<rounds;r++){for(let i=0;i<half;i++){const a=arr[i],b=arr[n-1-i];if(!a||!b)continue;for(const [h,aw] of [[a,b],[b,a]]){const key=`${h}|${aw}`;if(existing.has(key))continue;const ref=db.collection('fixtures').doc();batch.set(ref,{competition:comp,homeTeam:h,awayTeam:aw,round:`Matchday ${r+1}`,date:'',seasonId:SEASON_ID,createdAt:firebase.firestore.FieldValue.serverTimestamp()});existing.add(key);count++;}}arr=[arr[0],arr[n-1],...arr.slice(1,n-1)];}await batch.commit();await loadData();alert(`${count} fixtures generated for ${comp}.`);}
function adminResults(c){const pending=state.fixtures.filter(f=>!score(f));c.innerHTML=`<div class="admin-heading"><div><p class="eyebrow">RESULTS CENTER</p><h2>Enter results</h2><p>Score unapo hapa, public standings zinabadilika automatically.</p></div></div><div class="result-list">${pending.map(f=>`<div class="result-row"><span>${logo(teamsInFixture(f)[0],true)} ${esc(teamsInFixture(f)[0])}</span><input type="number" min="0" id="h-${f.id}" placeholder="0"><b>vs</b><input type="number" min="0" id="a-${f.id}" placeholder="0"><span>${esc(teamsInFixture(f)[1])} ${logo(teamsInFixture(f)[1],true)}</span><button class="mini-btn" onclick="saveResult('${f.id}')">Save</button></div>`).join('')||'<p class="muted">All published fixtures have results.</p>'}</div><h3 class="subhead">Published results</h3><div class="admin-list">${state.fixtures.filter(f=>score(f)).map(f=>fixtureHtml(f,true)).join('')}</div>`;}
window.saveResult=async id=>{const h=$(`h-${id}`).value,a=$(`a-${id}`).value;if(h===''||a==='')return alert('Enter both scores.');await adminSave('fixtures',id,{homeScore:Number(h),awayScore:Number(a),status:'played'});adminTab('results');};
window.editFixture=async id=>{const f=state.fixtures.find(x=>x.id===id);if(!f)return;const h=prompt('Home team',f.homeTeam||f.home||'');const a=prompt('Away team',f.awayTeam||f.away||'');if(h===null||a===null)return;await adminSave('fixtures',id,{homeTeam:h.trim(),awayTeam:a.trim()});adminTab('fixtures');};
window.deleteFixture=id=>adminDelete('fixtures',id);
function adminPromotion(c){
 const pl=table('Premier League'),ch=table('Championship');
 const relegated=pl.slice(-3).map(x=>x.team),promoted=ch.slice(0,3).map(x=>x.team);
 c.innerHTML=`<div class="admin-heading"><div><p class="eyebrow">SEASON MOVEMENT</p><h2>Promotion & Relegation</h2><p>Run this at the end of the Season. Bottom 3 PL → Championship; Top 3 Championship → PL.</p></div><button class="primary" id="applyMovement">Apply Movement</button></div><div class="movement-grid"><div class="movement-card"><h3>Relegated to Championship</h3>${relegated.map((x,i)=>`<div>${i+1}. ${logo(x,true)} <b>${esc(x)}</b></div>`).join('')||'<p>No PL table yet.</p>'}</div><div class="movement-card"><h3>Promoted to Premier League</h3>${promoted.map((x,i)=>`<div>${i+1}. ${logo(x,true)} <b>${esc(x)}</b></div>`).join('')||'<p>No Championship table yet.</p>'}</div></div><div class="admin-note"><b>Important:</b> UCL membership is not removed by promotion/relegation. A club can play UCL and a domestic league in the same Season.</div>`;
 $('applyMovement').onclick=async()=>{if(relegated.length<3||promoted.length<3)return alert('Both leagues need at least 3 ranked teams with results.');if(!confirm('Apply promotion/relegation now? This changes domestic league membership for these clubs.'))return;try{const batch=db.batch();const names=new Set([...relegated,...promoted]);for(const name of names){const t=state.teams.find(x=>x.name===name)||catalog.find(x=>x.name===name);if(!t)continue;let cs=teamCompetitions(t).filter(x=>x!=='Premier League'&&x!=='Championship');if(relegated.includes(name))cs.push('Championship');if(promoted.includes(name))cs.push('Premier League');const ref=db.collection('teams').doc(name.toLowerCase().replace(/[^a-z0-9]+/g,'-'));batch.set(ref,{competitions:[...new Set(cs)],competition:cs[0]||'UCL',seasonId:SEASON_ID},{merge:true});}await batch.commit();await loadData();alert('Promotion & relegation applied.');adminTab('promotion');}catch(e){console.error(e);alert('Could not apply movement. Check Firestore Rules.');}};
}
function adminNews(c){c.innerHTML=`<div class="admin-heading"><div><p class="eyebrow">PUBLISH</p><h2>News & Announcements</h2></div></div><div class="admin-form"><input id="newsTitle" placeholder="Headline"><input id="newsDate" type="date"><textarea id="newsBody" placeholder="Write announcement..."></textarea><button class="primary" id="saveNews">Publish Announcement</button></div><div class="admin-list">${state.news.map(n=>`<article class="admin-item"><b>${esc(n.title)}</b><span>${esc(n.date||'')}</span><p>${esc(n.body||n.content||'')}</p><button class="mini-btn danger" onclick="deleteNews('${n.id}')">Delete</button></article>`).join('')}</div>`;$('saveNews').onclick=async()=>{await adminSave('news',null,{title:$('newsTitle').value.trim(),date:$('newsDate').value,body:$('newsBody').value.trim(),seasonId:SEASON_ID});adminTab('news');};}
window.deleteNews=id=>adminDelete('news',id);
function adminHall(c){c.innerHTML=`<div class="admin-heading"><div><p class="eyebrow">LEGACY</p><h2>Hall of Fame</h2><p>Record champions by competition and Season.</p></div></div><div class="admin-form"><input id="hallSeason" value="${esc(state.season?.name||DEFAULT_SEASON)}" placeholder="Season"><select id="hallComp"><option>Premier League</option><option>Championship</option><option>UCL</option></select><input id="hallWinner" placeholder="Champion / Team"><input id="hallDate" type="date"><button class="primary" id="saveHall">Add Champion</button></div><div class="admin-list">${state.hall.map(h=>`<article class="admin-item"><b>🏆 ${esc(h.winner||h.team)}</b><span>${esc(h.season||'Season')} • ${esc(h.competition||'')}</span></article>`).join('')}</div>`;$('saveHall').onclick=async()=>{await adminSave('hallOfFame',null,{season:$('hallSeason').value.trim(),competition:$('hallComp').value,winner:$('hallWinner').value.trim(),date:$('hallDate').value,seasonId:SEASON_ID});adminTab('hall');};}
function adminSeason(c){const s=state.season||{};c.innerHTML=`<div class="admin-heading"><div><p class="eyebrow">SEASON MANAGEMENT</p><h2>Season settings</h2></div></div><div class="admin-form"><input id="seasonName" value="${esc(s.name||DEFAULT_SEASON)}" placeholder="Season name"><select id="seasonStatus"><option ${s.status==='Upcoming'?'selected':''}>Upcoming</option><option ${s.status==='Ongoing'?'selected':''}>Ongoing</option><option ${s.status==='Completed'?'selected':''}>Completed</option></select><input id="seasonYear" value="${esc(s.year||'2026')}" placeholder="Year"><button class="primary" id="saveSeason">Save Season</button></div>`;$('saveSeason').onclick=async()=>{const active=state.season?.activeCompetitions||['Premier League','Championship','UCL'];await adminSave('seasons',SEASON_ID,{name:$('seasonName').value.trim(),status:$('seasonStatus').value,year:$('seasonYear').value,current:true,activeCompetitions:active});adminTab('season');};}
'''
s=s[:start]+new+s[end:]
p.write_text(s)
