/* Gosper Global eFootball League — functional dashboard + Firebase admin/registration */
const firebaseConfig = {
  apiKey: "AIzaSyChZ12uOT7E1Pn-N1XlWUgpaUKA62QHiVU",
  authDomain: "gospel-global-efootball.firebaseapp.com",
  projectId: "gospel-global-efootball",
  storageBucket: "gospel-global-efootball.firebasestorage.app",
  messagingSenderId: "274171168871",
  appId: "1:274171168871:web:fc0e74fea03e173d436cc2"
};
firebase.initializeApp(firebaseConfig);
const auth=firebase.auth(), db=firebase.firestore();
const SEASON_ID='season-1', DEFAULT_SEASON='Season 1';

// Logos are stored with the team, so the same logo is reused in registration, tables and fixtures.
const catalog=[
// ENGLAND — TOP 6
['Liverpool','Premier League','https://images.fotmob.com/image_resources/logo/teamlogo/8650.png'],['Arsenal','Premier League','https://images.fotmob.com/image_resources/logo/teamlogo/9825.png'],['Manchester City','Premier League','https://images.fotmob.com/image_resources/logo/teamlogo/8456.png'],['Manchester United','Premier League','https://images.fotmob.com/image_resources/logo/teamlogo/10260.png'],['Chelsea','Premier League','https://images.fotmob.com/image_resources/logo/teamlogo/8455.png'],['Tottenham Hotspur','Premier League','https://images.fotmob.com/image_resources/logo/teamlogo/8586.png'],
// SPAIN — TOP 6
['Real Madrid','LaLiga','https://images.fotmob.com/image_resources/logo/teamlogo/8633.png'],['Barcelona','LaLiga','https://images.fotmob.com/image_resources/logo/teamlogo/8634.png'],['Atletico Madrid','LaLiga','https://images.fotmob.com/image_resources/logo/teamlogo/9906.png'],['Athletic Bilbao','LaLiga','https://images.fotmob.com/image_resources/logo/teamlogo/10205.png'],['Sevilla','LaLiga','https://images.fotmob.com/image_resources/logo/teamlogo/8302.png'],['Valencia','LaLiga','https://images.fotmob.com/image_resources/logo/teamlogo/8661.png'],
// ITALY — TOP 6
['Inter','Serie A','https://images.fotmob.com/image_resources/logo/teamlogo/8636.png'],['AC Milan','Serie A','https://images.fotmob.com/image_resources/logo/teamlogo/8564.png'],['Juventus','Serie A','https://images.fotmob.com/image_resources/logo/teamlogo/9885.png'],['Napoli','Serie A','https://images.fotmob.com/image_resources/logo/teamlogo/9875.png'],['Roma','Serie A','https://images.fotmob.com/image_resources/logo/teamlogo/8686.png'],['Lazio','Serie A','https://images.fotmob.com/image_resources/logo/teamlogo/8543.png'],
// GERMANY — TOP 6
['Bayern Munich','Bundesliga','https://images.fotmob.com/image_resources/logo/teamlogo/9823.png'],['Borussia Dortmund','Bundesliga','https://images.fotmob.com/image_resources/logo/teamlogo/9789.png'],['Bayer Leverkusen','Bundesliga','https://images.fotmob.com/image_resources/logo/teamlogo/8178.png'],['RB Leipzig','Bundesliga','https://images.fotmob.com/image_resources/logo/teamlogo/178475.png'],['Eintracht Frankfurt','Bundesliga','https://images.fotmob.com/image_resources/logo/teamlogo/9810.png'],['VfB Stuttgart','Bundesliga','https://images.fotmob.com/image_resources/logo/teamlogo/10269.png'],
// FRANCE — TOP 6
['Paris Saint-Germain','Ligue 1','https://images.fotmob.com/image_resources/logo/teamlogo/9847.png'],['Marseille','Ligue 1','https://images.fotmob.com/image_resources/logo/teamlogo/8592.png'],['Lyon','Ligue 1','https://images.fotmob.com/image_resources/logo/teamlogo/9748.png'],['Monaco','Ligue 1','https://images.fotmob.com/image_resources/logo/teamlogo/9829.png'],['Lille','Ligue 1','https://images.fotmob.com/image_resources/logo/teamlogo/8630.png'],['Nice','Ligue 1','https://images.fotmob.com/image_resources/logo/teamlogo/9831.png'],
// NETHERLANDS — TOP 6
['Ajax','Eredivisie','https://images.fotmob.com/image_resources/logo/teamlogo/8590.png'],['PSV Eindhoven','Eredivisie','https://images.fotmob.com/image_resources/logo/teamlogo/8640.png'],['Feyenoord','Eredivisie','https://images.fotmob.com/image_resources/logo/teamlogo/10229.png'],['AZ Alkmaar','Eredivisie','https://images.fotmob.com/image_resources/logo/teamlogo/10228.png'],['FC Twente','Eredivisie','https://images.fotmob.com/image_resources/logo/teamlogo/8614.png'],['FC Utrecht','Eredivisie','https://images.fotmob.com/image_resources/logo/teamlogo/8615.png'],
// TANZANIA — NBC PREMIER LEAGUE TOP 6
['Simba SC','NBC Premier League',''],['Yanga SC','NBC Premier League',''],['Azam FC','NBC Premier League',''],['Singida Black Stars','NBC Premier League',''],['Coastal Union','NBC Premier League',''],['KMC FC','NBC Premier League',''],
// EGYPT — TOP 6
['Al Ahly','Egypt League',''],['Zamalek','Egypt League',''],['Pyramids FC','Egypt League',''],['Al Masry','Egypt League',''],['Future FC','Egypt League',''],['Ismaily','Egypt League',''],
// CHAMPIONSHIP — smaller clubs from England, Spain, Germany and Italy
['Everton','Championship','https://images.fotmob.com/image_resources/logo/teamlogo/8668.png'],['West Ham United','Championship','https://images.fotmob.com/image_resources/logo/teamlogo/8654.png'],['Fulham','Championship','https://images.fotmob.com/image_resources/logo/teamlogo/9879.png'],['Crystal Palace','Championship','https://images.fotmob.com/image_resources/logo/teamlogo/9826.png'],
['Real Betis','Championship','https://images.fotmob.com/image_resources/logo/teamlogo/8603.png'],['Villarreal','Championship','https://images.fotmob.com/image_resources/logo/teamlogo/10268.png'],['Real Sociedad','Championship','https://images.fotmob.com/image_resources/logo/teamlogo/8560.png'],['Celta Vigo','Championship','https://images.fotmob.com/image_resources/logo/teamlogo/8662.png'],
['Borussia Monchengladbach','Championship','https://images.fotmob.com/image_resources/logo/teamlogo/9788.png'],['Werder Bremen','Championship','https://images.fotmob.com/image_resources/logo/teamlogo/8697.png'],['Wolfsburg','Championship','https://images.fotmob.com/image_resources/logo/teamlogo/8721.png'],['Mainz 05','Championship','https://images.fotmob.com/image_resources/logo/teamlogo/9905.png'],
['Atalanta','Championship','https://images.fotmob.com/image_resources/logo/teamlogo/8524.png'],['Fiorentina','Championship','https://images.fotmob.com/image_resources/logo/teamlogo/8535.png'],['Bologna','Championship','https://images.fotmob.com/image_resources/logo/teamlogo/9857.png'],['Torino','Championship','https://images.fotmob.com/image_resources/logo/teamlogo/9804.png']
].map(([name,competition,logo])=>({name,competition,logo}));

const state={teams:[],players:[],fixtures:[],news:[],hall:[],season:null,admin:false};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const initials=s=>String(s||'?').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function dateObj(v){if(!v)return null; if(v.toDate)return v.toDate(); const d=new Date(v); return isNaN(d)?null:d;}
function dateText(v){const d=dateObj(v);return d?d.toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):'TBA';}
function logoUrl(name){const t=state.teams.find(x=>x.name===name)||catalog.find(x=>x.name===name);return t?.logo||'';}
function logo(name,small=false){const src=logoUrl(name);return src?`<span class="logo-box ${small?'sm':''}"><img class="team-logo ${small?'sm':''}" src="${src}" alt="${esc(name)} logo" loading="lazy" onerror="this.parentElement.classList.add('failed');this.remove()"><span class="logo-fallback ${small?'sm':''}">${esc(initials(name))}</span></span>`:`<span class="logo-box ${small?'sm':''}"><span class="logo-fallback ${small?'sm':''}">${esc(initials(name))}</span></span>`}

function go(page){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.dataset.pageContent===page));document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('sidebar')?.classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});if(page==='teams')renderTeams();if(page==='fixtures')renderFixtures();if(page==='standings')renderStandings();if(page==='players')renderPlayers();if(page==='hall')renderHall();if(page==='news')renderNews();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-page]');if(b)go(b.dataset.page);});
$('mobileMenu')?.addEventListener('click',()=>$('sidebar').classList.toggle('open'));
$('registerCta')?.addEventListener('click',openRegister);$('registerPlayerBtn')?.addEventListener('click',openRegister);$('closeRegister')?.addEventListener('click',closeRegister);$('registerModal')?.addEventListener('click',e=>{if(e.target===$('registerModal'))closeRegister()});
$('competition')?.addEventListener('change',()=>populateClubPicker($('clubSearch').value));$('clubSearch')?.addEventListener('input',()=>populateClubPicker($('clubSearch').value));$('teamSearch')?.addEventListener('input',renderTeams);$('fixtureCompetition')?.addEventListener('change',renderFixtures);$('fixtureStatus')?.addEventListener('change',renderFixtures);$('standingsCompetition')?.addEventListener('change',renderStandings);$('globalSearch')?.addEventListener('input',searchSite);
document.querySelectorAll('.competition-card').forEach(c=>c.addEventListener('click',()=>{go('competitions');showCompetition(c.dataset.competition)}));

function openRegister(){ $('registerModal').hidden=false; populateClubPicker(''); setTimeout(()=>$('name')?.focus(),60); }
function closeRegister(){ $('registerModal').hidden=true; if($('registrationMsg')){$('registrationMsg').textContent='';$('registrationMsg').className='form-msg';} }
function teamCompetitions(t){return Array.isArray(t.competitions)&&t.competitions.length?t.competitions:(t.competition?[t.competition]:[])}
function isCompActive(comp){const a=state.season?.activeCompetitions;return !Array.isArray(a)||!a.length||a.includes(comp)}
function teamObjects(comp){
 if(comp==='UCL'){
  const groups=Array.isArray(state.season?.uclGroups)?state.season.uclGroups:[];
  const names=[...new Set(groups.flatMap(g=>Array.isArray(g.teams)?g.teams:[]))];
  return names.map(name=>{const base=catalog.find(t=>t.name===name)||{};const saved=state.teams.find(x=>x.name===name)||{};return {...base,...saved,name,competition:'UCL',competitions:['UCL'],enabled:saved.enabled!==false};}).filter(t=>t.name&&t.enabled!==false);
 }
 const merged=catalog.map(base=>{const saved=state.teams.find(x=>x.name===base.name);return {...base,...(saved||{}),logo:saved?.logo||base.logo,competition:saved?.competition||base.competition,competitions:Array.isArray(saved?.competitions)&&saved.competitions.length?saved.competitions:[base.competition]};});
 return merged.filter(t=>t.enabled!==false&&(!comp||teamCompetitions(t).includes(comp)));
}
function catalogObjects(){return catalog.slice();}
const MAJOR_LEAGUES=['Premier League','LaLiga','Serie A','Bundesliga','Ligue 1','Eredivisie','NBC Premier League','Egypt League'];
const ALL_COMPETITIONS=[...MAJOR_LEAGUES,'Championship','UCL'];
function qualifiedUCLTeams(){return MAJOR_LEAGUES.flatMap(league=>table(league).slice(0,2).map((r,i)=>({name:r.team,league,rank:i+1})));}
function currentUCLGroups(){return Array.isArray(state.season?.uclGroups)?state.season.uclGroups:[];}

function activeTeams(comp){return teamObjects(comp).filter(t=>isCompActive(comp))}
function populateClubPicker(q=''){const comp=$('competition').value, query=q.toLowerCase();const teams=activeTeams(comp).filter(t=>t.name.toLowerCase().includes(query));$('club').innerHTML=teams.map(t=>`<option value="${esc(t.name)}">${esc(t.name)}</option>`).join('');}
async function ensureAnon(){if(auth.currentUser)return true;try{await auth.signInAnonymously();return true}catch(e){console.error(e);return false}}
$('registrationForm')?.addEventListener('submit',async e=>{e.preventDefault();const m=$('registrationMsg');m.className='form-msg';m.textContent='Registering…';if(!(await ensureAnon())){m.className='form-msg error';m.textContent='Firebase Anonymous sign-in is not enabled.';return;}const name=$('name').value.trim(),raw=$('pid').value.trim(),key=raw.toLowerCase().replace(/\s+/g,''),competition=$('competition').value,club=$('club').value;if(!name||!key||!club){m.className='form-msg error';m.textContent='Fill all required fields.';return;}const ref=db.collection('players').doc(`${SEASON_ID}_${key.replace(/[^a-z0-9_-]/g,'_')}`);try{const snap=await ref.get();if(snap.exists){m.className='form-msg error';m.textContent=`Already registered with ${snap.data().club||'another club'} for ${state.season?.name||DEFAULT_SEASON}.`;return;}await ref.set({name,playerId:raw,playerIdKey:key,competition,club,seasonId:SEASON_ID,status:'active',createdAt:firebase.firestore.FieldValue.serverTimestamp()});m.className='form-msg ok';m.textContent=`Registration successful — ${club}`;e.target.reset();populateClubPicker('');await loadData();setTimeout(closeRegister,900);}catch(err){console.error(err);m.className='form-msg error';m.textContent='Registration failed. Check Firestore Rules.';}});

async function getAll(c){try{const s=await db.collection(c).get();return s.docs.map(d=>({id:d.id,...d.data()}));}catch(e){console.warn(c,e);return[];}}
async function loadData(){const [teams,players,fixtures,news,hall,seasons]=await Promise.all(['teams','players','fixtures','news','hallOfFame','seasons'].map(getAll));state.teams=teams;state.players=players.filter(p=>p.seasonId===SEASON_ID||!p.seasonId);state.fixtures=fixtures;state.news=news;state.hall=hall;state.season=seasons.find(s=>s.id===SEASON_ID)||seasons.find(s=>s.current===true)||{id:SEASON_ID,name:DEFAULT_SEASON,status:'Ongoing'};renderAll();if(state.admin)renderAdmin();}
function score(f){const h=f.homeScore??f.homeGoals,a=f.awayScore??f.awayGoals;return h!==undefined&&h!==null&&a!==undefined&&a!==null&&h!==''&&a!==''?{h:+h,a:+a}:null;}
function teamsInFixture(f){return [f.homeTeam||f.home||f.teamA||'',f.awayTeam||f.away||f.teamB||''];}
function compOf(f){return f.competition||'Premier League';}
function table(comp){const map=new Map(teamObjects(comp).map(t=>[t.name,{team:t.name,mp:0,w:0,d:0,l:0,gf:0,ga:0,gd:0,pts:0}]));state.fixtures.filter(f=>compOf(f)===comp&&score(f)&&map.has((f.homeTeam||f.home))&&map.has((f.awayTeam||f.away))).forEach(f=>{const s=score(f),[h,a]=teamsInFixture(f);if(!map.has(h))map.set(h,{team:h,mp:0,w:0,d:0,l:0,gf:0,ga:0,gd:0,pts:0});if(!map.has(a))map.set(a,{team:a,mp:0,w:0,d:0,l:0,gf:0,ga:0,gd:0,pts:0});const H=map.get(h),A=map.get(a);H.mp++;A.mp++;H.gf+=s.h;H.ga+=s.a;A.gf+=s.a;A.ga+=s.h;if(s.h>s.a){H.w++;H.pts+=3;A.l++;}else if(s.a>s.h){A.w++;A.pts+=3;H.l++;}else{H.d++;A.d++;H.pts++;A.pts++;}});return [...map.values()].map(x=>({...x,gd:x.gf-x.ga})).sort((a,b)=>b.pts-a.pts||b.gd-a.gd||b.gf-a.gf||a.team.localeCompare(b.team));}
function rowHtml(r,i){return `<tr><td><b>${i+1}</b></td><td><div class="team-cell">${logo(r.team,true)}<b>${esc(r.team)}</b></div></td><td>${r.mp}</td><td>${r.w}</td><td>${r.d}</td><td>${r.l}</td><td>${r.gf}</td><td>${r.ga}</td><td>${r.gd}</td><td><b>${r.pts}</b></td></tr>`;}
function renderStandings(){const c=$('standingsCompetition')?.value||'Premier League';const rows=table(c);$('standingsTable').innerHTML=rows.length?rows.map(rowHtml).join(''):`<tr><td colspan="10" class="empty">No results published yet.</td></tr>`;}
function fixtureHtml(f,admin=false){const [h,a]=teamsInFixture(f),s=score(f);return `<article class="fixture-card"><div class="fixture-meta"><span class="competition-pill">${esc(compOf(f))}</span><span>${dateText(f.date||f.kickoff)}</span><span>${esc(f.round||'Match')}</span></div><div class="fixture-teams"><div class="fixture-team">${logo(h)}<strong>${esc(h)}</strong></div><div class="fixture-score"><b>${s?`${s.h} - ${s.a}`:'VS'}</b><small>${s?'FULL TIME':'UPCOMING'}</small></div><div class="fixture-team">${logo(a)}<strong>${esc(a)}</strong></div></div>${admin?`<div class="fixture-admin-actions"><button class="mini-btn" onclick="editFixture('${f.id}')">Edit</button><button class="mini-btn danger" onclick="deleteFixture('${f.id}')">Delete</button></div>`:''}</article>`;}
function renderFixtures(){let fs=state.fixtures.filter(f=>{const c=compOf(f);const [h,a]=teamsInFixture(f);return !!teamObjects(c).find(t=>t.name===h)&&!!teamObjects(c).find(t=>t.name===a);});const c=$('fixtureCompetition')?.value||'all',st=$('fixtureStatus')?.value||'all';if(c!=='all')fs=fs.filter(f=>compOf(f)===c);if(st==='upcoming')fs=fs.filter(f=>!score(f));if(st==='played')fs=fs.filter(f=>!!score(f));fs.sort((a,b)=>(dateObj(a.date||a.kickoff)||0)-(dateObj(b.date||b.kickoff)||0));$('fixturesList').innerHTML=fs.length?fs.map(f=>fixtureHtml(f)).join(''):`<div class="empty-block">No fixtures found.</div>`;}
function renderTeams(){const q=($('teamSearch')?.value||'').toLowerCase(),c=$('teamCompetition')?.value||'all';let ts=teamObjects().filter(t=>!q||t.name.toLowerCase().includes(q));if(c!=='all')ts=ts.filter(t=>teamCompetitions(t).includes(c));$('teamsGrid').innerHTML=ts.map(t=>`<article class="team-card"><div class="team-logo-wrap">${logo(t.name)}</div><div><h3>${esc(t.name)}</h3><p>${esc(t.competition||'Competition TBA')}</p></div><span class="status-dot ${t.enabled===false?'off':''}">${t.enabled===false?'Disabled':'Available'}</span></article>`).join('')||`<div class="empty-block">No teams found.</div>`;}
function renderPlayers(){const ps=state.players.slice().sort((a,b)=>String(a.name).localeCompare(String(b.name)));$('playersGrid').innerHTML=ps.length?ps.map(p=>`<article class="player-card"><div class="player-avatar">${esc(initials(p.name))}</div><div><h3>${esc(p.name)}</h3><p>${esc(p.club||'Club TBA')}</p><small>${esc(p.competition||'')} • ${esc(state.season?.name||DEFAULT_SEASON)}</small></div></article>`).join(''):`<div class="empty-block">No player registrations yet.</div>`;}
function renderHall(){const hs=state.hall.slice().sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));$('hallGrid').innerHTML=hs.length?hs.map(h=>`<article class="hall-card"><div class="trophy">🏆</div><span>${esc(h.season||h.seasonName||DEFAULT_SEASON)}</span><h2>${esc(h.winner||h.team||'Champion')}</h2><p>${esc(h.competition||'Competition')} ${h.date?'• '+esc(h.date):''}</p></article>`).join(''):`<div class="empty-block">No champions published yet.</div>`;}
function renderNews(){
 const ns=state.news.slice().sort((a,b)=>String(b.date||b.createdAt||'').localeCompare(String(a.date||a.createdAt||'')));
 if(!ns.length){$('newsGrid').innerHTML='<div class="news-empty"><div class="news-empty-icon">✦</div><h3>No news published yet</h3><p>The latest league announcements will appear here.</p></div>';return;}
 const featured=ns[0], rest=ns.slice(1);
 const fmtDate=n=>{const d=n.date?new Date(n.date+'T00:00:00'):null;return d&&!isNaN(d)?d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):(n.date||dateText(n.createdAt)||'LATEST');};
 const category=n=>n.category||n.competition||'League Update';
 const excerpt=(n,max=190)=>{const x=String(n.body||n.content||'');return x.length>max?x.slice(0,max).trim()+'…':x;};
 const card=n=>`<article class="news-modern-card"><div class="news-card-top"><span class="news-category">${esc(category(n))}</span><span class="news-date">${esc(fmtDate(n))}</span></div><div class="news-card-icon">⚽</div><h3>${esc(n.title||'League Update')}</h3><p>${esc(excerpt(n))}</p><div class="news-card-foot"><span>Gosper Global eFootball League</span><b>→</b></div></article>`;
 $('newsGrid').innerHTML=`<div class="news-ticker"><span class="ticker-label">LATEST</span><div class="ticker-text">${esc(featured.title||'League Update')}</div><span class="ticker-date">${esc(fmtDate(featured))}</span></div><article class="news-featured"><div class="news-featured-glow"></div><div class="news-featured-content"><div class="news-featured-meta"><span class="news-category bright">${esc(category(featured))}</span><span>${esc(fmtDate(featured))}</span></div><h2>${esc(featured.title||'League Update')}</h2><p>${esc(excerpt(featured,320))}</p><div class="news-featured-foot"><span>OFFICIAL LEAGUE ANNOUNCEMENT</span><span class="news-arrow">↗</span></div></div><div class="news-featured-mark">GG</div></article><div class="news-feed-head"><div><p class="eyebrow">LATEST STORIES</p><h2>From the League</h2></div><span>${ns.length} ${ns.length===1?'update':'updates'}</span></div><div class="news-feed">${rest.length?rest.map(card).join(''): '<div class="news-single-note">That’s the latest update. New announcements will appear here.</div>'}</div>`;
}
function renderDashboard(){const pl=table('Premier League');$('dashTable').innerHTML=pl.slice(0,6).map(rowHtml).join('')||`<tr><td colspan="10" class="empty">No standings yet.</td></tr>`;const up=state.fixtures.filter(f=>!score(f)).sort((a,b)=>(dateObj(a.date||a.kickoff)||0)-(dateObj(b.date||b.kickoff)||0)).slice(0,4);$('dashMatches').innerHTML=up.length?up.map(fixtureHtml).join(''):`<div class="empty-block">No fixtures published yet.</div>`;$('dashPlayers').textContent=state.players.length;$('dashFixtures').textContent=state.fixtures.length;$('dashPlayed').textContent=state.fixtures.filter(f=>score(f)).length;$('dashTeams').textContent=teamObjects().length;}
function renderAll(){renderDashboard();renderTeams();renderFixtures();renderStandings();renderPlayers();renderHall();renderNews();$('sideSeason').textContent=$('topSeason').textContent=$('footerSeason').textContent=state.season?.name||DEFAULT_SEASON;$('seasonStatus').textContent=state.season?.status||'Ongoing';}
function showCompetition(c){const teams=activeTeams(c);const groups=currentUCLGroups();const groupHtml=c==='UCL'&&groups.length?`<div class="detail-grid">${groups.map(g=>`<div><b>${esc(g.name)}</b><span>${(g.teams||[]).map(esc).join(' • ')}</span></div>`).join('')}</div>`:'';$('competitionDetail').innerHTML=`<div class="panel-head"><div><span class="eyebrow">${esc(c)}</span><h2>${esc(c)} Control</h2></div><button class="primary" id="detailRegister">Register Player</button></div><div class="detail-grid"><div><b>${teams.length}</b><span>${c==='UCL'?'Qualified clubs':'Available teams'}</span></div><div><b>${state.fixtures.filter(f=>compOf(f)===c).length}</b><span>Fixtures</span></div><div><b>${state.players.filter(p=>p.competition===c).length}</b><span>Players</span></div></div>${groupHtml}<div class="mini-team-list">${teams.slice(0,16).map(t=>`<span>${logo(t.name,true)}${esc(t.name)}</span>`).join('')}</div>`;$('detailRegister').onclick=()=>{openRegister();$('competition').value=c;populateClubPicker('');};}
function searchSite(e){const q=(e.target?.value||e||'').trim().toLowerCase();if(!q)return;const t=teamObjects().find(x=>x.name.toLowerCase().includes(q));const p=state.players.find(x=>String(x.name).toLowerCase().includes(q)||String(x.playerId).toLowerCase().includes(q));const f=state.fixtures.find(x=>teamsInFixture(x).some(n=>n.toLowerCase().includes(q)));if(t)go('teams');else if(p)go('players');else if(f)go('fixtures');}

// ---------- Admin ----------
$('adminLoginBtn')?.addEventListener('click',openAdminLogin);$('adminLoginBtn2')?.addEventListener('click',openAdminLogin);
function openAdminLogin(){
  const email=prompt('Admin email:'); if(!email)return;
  const password=prompt('Admin password:'); if(password===null)return;
  auth.signInWithEmailAndPassword(email.trim(),password).then(async()=>{state.admin=true;await loadData();go('admin');}).catch(e=>alert('Admin login failed. Check Firebase Authentication email/password.'));
}
async function adminSave(collection,id,data){
  const ref=db.collection(collection).doc(id||db.collection(collection).doc().id);
  await ref.set({...data,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});
  await loadData();
}
async function adminDelete(collection,id){if(!confirm('Delete this item?'))return;await db.collection(collection).doc(id).delete();await loadData();}
function renderAdmin(){
 const a=$('adminArea');
 if(!state.admin){a.innerHTML=`<div class="admin-lock"><div class="lock-icon">⚙</div><h2>Admin access required</h2><p>Sign in with your Firebase administrator account.</p><button class="primary" id="adminLoginBtn2">Sign in to Control Center</button></div>`;$('adminLoginBtn2').onclick=openAdminLogin;return;}
 a.innerHTML=`<div class="admin-shell"><div class="admin-nav"><button class="admin-tab active" data-admin-tab="overview">Overview</button><button class="admin-tab" data-admin-tab="competitions">Competitions</button><button class="admin-tab" data-admin-tab="teams">Teams</button><button class="admin-tab" data-admin-tab="fixtures">Fixtures</button><button class="admin-tab" data-admin-tab="ucl">UCL Groups</button><button class="admin-tab" data-admin-tab="results">Results</button><button class="admin-tab" data-admin-tab="members">Members</button><button class="admin-tab" data-admin-tab="promotion">Promotion / Relegation</button><button class="admin-tab" data-admin-tab="news">News</button><button class="admin-tab" data-admin-tab="hall">Hall of Fame</button><button class="admin-tab" data-admin-tab="season">Season</button><button class="ghost" id="adminSignOut">Sign out</button></div><div id="adminContent"></div></div>`;
 document.querySelectorAll('.admin-tab').forEach(b=>b.onclick=()=>adminTab(b.dataset.adminTab));$('adminSignOut').onclick=()=>auth.signOut().then(()=>{state.admin=false;renderAdmin();});adminTab('overview');
}
function adminTab(tab){
 document.querySelectorAll('.admin-tab').forEach(b=>b.classList.toggle('active',b.dataset.adminTab===tab));
 const c=$('adminContent');
 if(tab==='overview')adminOverview(c);if(tab==='competitions')adminCompetitions(c);if(tab==='teams')adminTeams(c);if(tab==='fixtures')adminFixtures(c);if(tab==='ucl')adminUCL(c);if(tab==='results')adminResults(c);if(tab==='members')adminMembers(c);if(tab==='promotion')adminPromotion(c);if(tab==='news')adminNews(c);if(tab==='hall')adminHall(c);if(tab==='season')adminSeason(c);
}
function adminOverview(c){
 const active=(state.season?.activeCompetitions||ALL_COMPETITIONS);
 c.innerHTML=`<div class="admin-grid"><div class="admin-stat"><b>${state.teams.length||catalog.length}</b><span>Clubs in system</span></div><div class="admin-stat"><b>${state.players.length}</b><span>Players</span></div><div class="admin-stat"><b>${state.fixtures.length}</b><span>Fixtures</span></div><div class="admin-stat"><b>${state.fixtures.filter(f=>score(f)).length}</b><span>Results entered</span></div></div><div class="admin-control-card"><div><p class="eyebrow">CURRENT SEASON</p><h2>${esc(state.season?.name||DEFAULT_SEASON)}</h2><p class="muted">Active competitions: ${active.map(esc).join(' • ')}</p></div><button class="primary" id="quickComp">Choose competitions</button></div><div class="admin-control-card"><div><p class="eyebrow">SEASON MOVEMENT</p><h2>Automatic promotion & relegation</h2><p class="muted">At season end: bottom 3 Premier League clubs move to Championship; top 3 Championship clubs move to Premier League.</p></div><button class="primary" id="quickMove">Open</button></div>`;
 $('quickComp').onclick=()=>adminTab('competitions');$('quickMove').onclick=()=>adminTab('promotion');
}
function adminCompetitions(c){
 const active=state.season?.activeCompetitions||ALL_COMPETITIONS;
 c.innerHTML=`<div class="admin-heading"><div><p class="eyebrow">COMPETITION CONTROL</p><h2>Season competition setup</h2><p>Eight major leagues have 6 clubs each. Championship contains smaller clubs. UCL clubs are created from the top 2 of every major league.</p></div></div><div class="competition-control-grid">${ALL_COMPETITIONS.map(x=>`<label class="competition-toggle"><input type="checkbox" data-active-comp="${x}" ${active.includes(x)?'checked':''}><span class="toggle-copy"><b>${x}</b><small>${x==='UCL'?'16 qualified clubs • 4 groups of 4 • Group Stage':'6 clubs • Home & Away'}</small></span><strong>${active.includes(x)?'ACTIVE':'OFF'}</strong></label>`).join('')}</div><div class="admin-actions-row"><button class="primary" id="saveActiveComps">Save Competition Setup</button></div>`;
 $('saveActiveComps').onclick=async()=>{const active=[...document.querySelectorAll('[data-active-comp]:checked')].map(x=>x.dataset.activeComp);if(!active.length)return alert('Select at least one competition.');await adminSave('seasons',SEASON_ID,{activeCompetitions:active});alert('Competition setup saved.');adminTab('competitions');};
}
function adminTeams(c){
 const all=catalogObjects();
 c.innerHTML=`<div class="admin-heading"><div><p class="eyebrow">CLUB CONTROL</p><h2>Official club pool</h2><p>Old UCL clubs are no longer part of the catalog. Use “Apply new club structure” once to sync Firestore and remove their UCL membership.</p></div><button class="primary" id="applyClubStructure">Apply new club structure</button></div><div class="admin-team-grid">${all.map(t=>{const saved=state.teams.find(x=>x.name===t.name)||{};const cs=teamCompetitions({...t,...saved});return `<div class="admin-team-card"><div class="admin-team-main">${logo(t.name)}<div><b>${esc(t.name)}</b><small>${esc(t.competition)}</small></div></div><div class="comp-checks"><label><input type="checkbox" data-team-comp="${t.competition}" data-team-name="${esc(t.name)}" checked disabled> ${esc(t.competition)}</label><label class="enable-check"><input type="checkbox" data-team-enabled="${esc(t.name)}" ${saved.enabled!==false?'checked':''}> Available</label></div></div>`}).join('')}</div>`;
 $('applyClubStructure').onclick=async()=>{if(!confirm('Apply the new club structure? This will disable old clubs outside the new catalog and remove old UCL memberships.'))return;try{const batch=db.batch();const wanted=new Set(all.map(t=>t.name));for(const old of state.teams){if(!wanted.has(old.name)){const ref=db.collection('teams').doc(old.id);batch.set(ref,{enabled:false,competitions:old.competitions||[],competition:old.competition||''},{merge:true});}}
 for(const t of all){const enabled=document.querySelector(`[data-team-enabled="${CSS.escape(t.name)}"]`).checked;const ref=db.collection('teams').doc(t.name.toLowerCase().replace(/[^a-z0-9]+/g,'-'));batch.set(ref,{name:t.name,competitions:[t.competition],competition:t.competition,logo:t.logo||'',enabled,seasonId:SEASON_ID},{merge:true});}
 await batch.commit();await adminSave('seasons',SEASON_ID,{activeCompetitions:ALL_COMPETITIONS});await loadData();alert('New club structure applied.');adminTab('teams');}catch(e){console.error(e);alert('Could not apply club structure. Check Firestore Rules.');}};
}
function adminFixtures(c){c.innerHTML=`<div class="admin-heading"><div><p class="eyebrow">FIXTURE ENGINE</p><h2>Domestic fixtures</h2><p>Generate Home & Away for any 6-team major league or the 16-team Championship. UCL group fixtures are generated in the UCL Groups tab.</p></div><div class="admin-actions"><select id="genComp">${[...MAJOR_LEAGUES,'Championship'].map(x=>`<option>${x}</option>`).join('')}</select><button class="primary" id="generateFixtures">Generate Home & Away</button></div></div><div class="form-grid admin-form"><select id="fxComp">${ALL_COMPETITIONS.map(x=>`<option>${x}</option>`).join('')}</select><input id="fxHome" placeholder="Home team"><input id="fxAway" placeholder="Away team"><input id="fxDate" type="date"><input id="fxRound" placeholder="Round / Matchday"><button class="primary" id="addFixture">Add Fixture</button></div><div class="admin-list">${state.fixtures.slice().sort((a,b)=>(dateObj(a.date)||0)-(dateObj(b.date)||0)).map(f=>fixtureHtml(f,true)).join('')||'<p class="muted">No fixtures yet.</p>'}</div>`;$('generateFixtures').onclick=()=>generateFixtures($('genComp').value);$('addFixture').onclick=async()=>{const id=db.collection('fixtures').doc().id;await adminSave('fixtures',id,{competition:$('fxComp').value,homeTeam:$('fxHome').value.trim(),awayTeam:$('fxAway').value.trim(),date:$('fxDate').value,round:$('fxRound').value||'Matchday',seasonId:SEASON_ID});adminTab('fixtures');};}
async function generateFixtures(comp){const ts=teamObjects(comp).map(t=>t.name);if(ts.length<2){alert('At least 2 teams are required.');return;}const existing=new Set(state.fixtures.filter(f=>compOf(f)===comp).map(f=>`${f.homeTeam||f.home}|${f.awayTeam||f.away}`));let arr=ts.slice();if(arr.length%2)arr.push(null);const n=arr.length,rounds=n-1,half=n/2,batch=db.batch();let count=0;for(let r=0;r<rounds;r++){for(let i=0;i<half;i++){const a=arr[i],b=arr[n-1-i];if(!a||!b)continue;for(const [h,aw] of [[a,b],[b,a]]){const key=`${h}|${aw}`;if(existing.has(key))continue;const ref=db.collection('fixtures').doc();batch.set(ref,{competition:comp,homeTeam:h,awayTeam:aw,round:`Matchday ${r+1}`,date:'',seasonId:SEASON_ID,createdAt:firebase.firestore.FieldValue.serverTimestamp()});existing.add(key);count++;}}arr=[arr[0],arr[n-1],...arr.slice(1,n-1)];}await batch.commit();await loadData();alert(`${count} fixtures generated for ${comp}.`);}
function uclAutoGroups(qualified){
 const groups=[{name:'Group A',teams:[]},{name:'Group B',teams:[]},{name:'Group C',teams:[]},{name:'Group D',teams:[]}];
 // Seed first-place qualifiers first, then second-place qualifiers with a rotation
 // that avoids putting the same domestic league in the same group where possible.
 const first=qualified.filter(x=>x.rank===1), second=qualified.filter(x=>x.rank===2);
 first.forEach((x,i)=>groups[i%4].teams.push(x.name));
 second.forEach((x,i)=>{let start=(i+2)%4;for(let k=0;k<4;k++){const gi=(start+k)%4;const leagues=groups[gi].teams.map(n=>qualified.find(q=>q.name===n)?.league);if(!leagues.includes(x.league)&&groups[gi].teams.length<4){groups[gi].teams.push(x.name);return;}}for(const g of groups)if(g.teams.length<4){g.teams.push(x.name);return;}});
 return groups;
}
function adminUCL(c){
 const groups=currentUCLGroups(); const q=qualifiedUCLTeams();
 const groupNames=['Group A','Group B','Group C','Group D'];
 const options=q.map(x=>`<option value="${esc(x.name)}">${esc(x.name)} — ${esc(x.league)} (${x.rank===1?'1st':'2nd'})</option>`).join('');
 c.innerHTML=`<div class="admin-heading"><div><p class="eyebrow">UCL CONTROL</p><h2>Champions League Group Stage</h2><p>Top 2 from each of the 8 major leagues qualify. Build 4 groups of 4, save the draw, then generate Home & Away group fixtures.</p></div><div class="admin-actions"><button class="primary" id="autoUCL">Auto-generate Groups</button><button class="ghost" id="saveUCL">Save Groups</button><button class="primary" id="genUCLFixtures">Generate UCL Fixtures</button></div></div>
 <div class="admin-note"><b>Qualified teams detected: ${q.length}/16</b><p>${q.length<16?'Complete/publish domestic league results first so every major league has two qualified clubs.':'All 16 qualification places are currently available.'}</p></div>
 <div class="admin-team-grid">${groups.length===4?groups.map((g,gi)=>`<div class="admin-team-card"><div class="admin-team-main"><div class="logo-box"><span class="logo-fallback" style="display:grid">${String.fromCharCode(65+gi)}</span></div><div><b>${esc(g.name||groupNames[gi])}</b><small>4 clubs required</small></div></div><div class="admin-form" style="padding:12px 0 0">${[0,1,2,3].map(i=>`<select data-ucl-group="${gi}" data-ucl-slot="${i}"><option value="">Select club</option>${options}</select>`).join('')}</div></div>`).join(''):`<div class="empty-block">No UCL draw saved yet. Click “Auto-generate Groups” after 16 qualifiers are available.</div>`}</div>
 <div class="admin-list"><h3>Qualification snapshot</h3>${q.map((x,i)=>`<article class="admin-item"><b>${i+1}. ${esc(x.name)}</b><span>${esc(x.league)} • ${x.rank===1?'1st':'2nd'}</span></article>`).join('')||'<p class="muted">No qualified teams yet.</p>'}</div>`;
 function fill(){const gs=currentUCLGroups(); document.querySelectorAll('[data-ucl-group]').forEach(sel=>{const gi=+sel.dataset.uclGroup,si=+sel.dataset.uclSlot;sel.value=gs[gi]?.teams?.[si]||'';});}
 fill();
 $('autoUCL').onclick=()=>{if(q.length!==16)return alert('UCL needs 16 qualified teams: top 2 from each of the 8 major leagues.');const ng=uclAutoGroups(q);state.season={...(state.season||{}),uclGroups:ng};adminUCL(c);};
 $('saveUCL').onclick=async()=>{const ng=groupNames.map((name,gi)=>({name,teams:[0,1,2,3].map(si=>document.querySelector(`[data-ucl-group="${gi}"][data-ucl-slot="${si}"]`)?.value||'').filter(Boolean)}));const all=ng.flatMap(g=>g.teams);if(ng.some(g=>g.teams.length!==4)||new Set(all).size!==16)return alert('Each UCL group must contain 4 different qualified clubs, with 16 clubs total.');await adminSave('seasons',SEASON_ID,{uclGroups:ng,uclGroupsLocked:true});alert('UCL groups saved.');adminTab('ucl');};
 $('genUCLFixtures').onclick=async()=>{const gs=currentUCLGroups();if(gs.length!==4||gs.some(g=>g.teams.length!==4))return alert('Save four complete UCL groups first.');const existing=new Set(state.fixtures.filter(f=>compOf(f)==='UCL'&&String(f.stage||'').toLowerCase()==='group stage').map(f=>`${f.homeTeam||f.home}|${f.awayTeam||f.away}`));const batch=db.batch();let count=0;for(const g of gs){const ts=g.teams;for(let i=0;i<ts.length;i++)for(let j=i+1;j<ts.length;j++)for(const [h,a] of [[ts[i],ts[j]],[ts[j],ts[i]]]){const key=`${h}|${a}`;if(existing.has(key))continue;const ref=db.collection('fixtures').doc();batch.set(ref,{competition:'UCL',stage:'Group Stage',group:g.name,homeTeam:h,awayTeam:a,date:'',round:`${g.name} Match`,seasonId:SEASON_ID,createdAt:firebase.firestore.FieldValue.serverTimestamp()});existing.add(key);count++;}}await batch.commit();await loadData();alert(`${count} UCL Group Stage fixtures generated.`);adminTab('ucl');};
}
function adminResults(c){
 const comp=$('resultComp')?.value||'all'; const fs=state.fixtures.filter(f=>comp==='all'||compOf(f)===comp);
 c.innerHTML=`<div class="admin-heading"><div><p class="eyebrow">RESULTS CONTROL</p><h2>Enter match results</h2><p>Save scores directly to published fixtures. Tables update automatically.</p></div><select id="resultComp">${ALL_COMPETITIONS.map(x=>`<option ${x===comp?'selected':''}>${x}</option>`).join('')}<option value="all" ${comp==='all'?'selected':''}>All competitions</option></select></div><div class="result-list">${fs.map(f=>{const s=score(f)||{};const [h,a]=teamsInFixture(f);return `<div class="result-row"><div>${logo(h,true)} ${esc(h)}</div><input type="number" min="0" id="rh_${esc(f.id)}" value="${s.h??''}" placeholder="-"/><b>:</b><input type="number" min="0" id="ra_${esc(f.id)}" value="${s.a??''}" placeholder="-"/><div>${esc(a)} ${logo(a,true)}</div><button class="mini-btn" data-save-result="${esc(f.id)}">Save</button></div>`;}).join('')||'<p class="muted">No fixtures found.</p>'}</div>`;
 $('resultComp').onchange=e=>adminResults(c);document.querySelectorAll('[data-save-result]').forEach(b=>b.onclick=async()=>{const id=b.dataset.saveResult,h=$(`rh_${id}`).value,a=$(`ra_${id}`).value;if(h===''||a===''||+h<0||+a<0)return alert('Enter both scores.');b.disabled=true;b.textContent='Saving…';try{await adminSave('fixtures',id,{homeScore:+h,awayScore:+a,played:true});adminResults(c);}catch(e){console.error(e);alert('Could not save result.');b.disabled=false;b.textContent='Save';}});
}
function adminPromotion(c){
 const pl=table('Premier League'), ch=table('Championship'); const relegated=pl.slice(-3), promoted=ch.slice(0,3);
 c.innerHTML=`<div class="admin-heading"><div><p class="eyebrow">SEASON MOVEMENT</p><h2>Promotion / Relegation</h2><p>Preview the bottom 3 of Premier League and top 3 of Championship from current published results.</p></div><button class="primary" id="applyMovement">Apply Movement</button></div><div class="two-col"><div class="panel"><div class="panel-head"><h2>Relegation</h2></div><div class="admin-list">${relegated.map((r,i)=>`<article class="admin-item"><b>${i+1}. ${esc(r.team)}</b><span>${r.pts} pts</span></article>`).join('')||'<p class="muted">Not enough Premier League clubs/results.</p>'}</div></div><div class="panel"><div class="panel-head"><h2>Promotion</h2></div><div class="admin-list">${promoted.map((r,i)=>`<article class="admin-item"><b>${i+1}. ${esc(r.team)}</b><span>${r.pts} pts</span></article>`).join('')||'<p class="muted">Not enough Championship clubs/results.</p>'}</div></div></div>`;
 $('applyMovement').onclick=async()=>{if(relegated.length!==3||promoted.length!==3)return alert('Both competitions need enough clubs before movement can be applied.');if(!confirm(`Move ${promoted.map(x=>x.team).join(', ')} to Premier League and ${relegated.map(x=>x.team).join(', ')} to Championship?`))return;try{const batch=db.batch();for(const r of relegated){const ref=db.collection('teams').doc(r.team.toLowerCase().replace(/[^a-z0-9]+/g,'-'));batch.set(ref,{name:r.team,competition:'Championship',competitions:['Championship'],seasonId:SEASON_ID},{merge:true});}for(const r of promoted){const ref=db.collection('teams').doc(r.team.toLowerCase().replace(/[^a-z0-9]+/g,'-'));batch.set(ref,{name:r.team,competition:'Premier League',competitions:['Premier League'],seasonId:SEASON_ID},{merge:true});}await batch.commit();await loadData();alert('Promotion and relegation applied.');adminTab('promotion');}catch(e){console.error(e);alert('Could not apply movement. Check Firestore Rules.');}};
}
function adminNews(c){c.innerHTML=`<div class="admin-heading"><div><p class="eyebrow">PUBLISH</p><h2>News & Announcements</h2><p>Publish updates that appear on the public News page.</p></div></div><div class="admin-form"><input id="newsTitle" placeholder="Headline"><input id="newsDate" type="date"><textarea id="newsBody" placeholder="Write announcement..."></textarea><button class="primary" id="saveNews">Publish Announcement</button></div><div class="admin-list">${state.news.map(n=>`<article class="admin-item"><b>${esc(n.title)}</b><span>${esc(n.date||'')}</span><p>${esc(n.body||n.content||'')}</p><button class="mini-btn danger" onclick="deleteNews('${n.id}')">Delete</button></article>`).join('')||'<p class="muted">No news published yet.</p>'}</div>`;$('saveNews').onclick=async()=>{const title=$('newsTitle').value.trim(),body=$('newsBody').value.trim();if(!title||!body)return alert('Headline and announcement text are required.');const btn=$('saveNews');btn.disabled=true;btn.textContent='Publishing…';try{await adminSave('news',null,{title,date:$('newsDate').value,body,seasonId:SEASON_ID,createdAt:firebase.firestore.FieldValue.serverTimestamp()});alert('News published successfully.');adminTab('news');}catch(e){console.error(e);alert('News could not be published. Make sure you are signed in as admin and the latest Firestore Rules are published.');btn.disabled=false;btn.textContent='Publish Announcement';}};}
function adminMembers(c){const ps=state.players.slice().sort((a,b)=>String(a.name).localeCompare(String(b.name)));c.innerHTML=`<div class="admin-heading"><div><p class="eyebrow">PLAYER MANAGEMENT</p><h2>Registered Members</h2><p>Remove a registration when necessary. This deletes the member from the current Season.</p></div></div><div class="admin-list">${ps.map(p=>`<article class="admin-item member-admin-item"><div><b>${esc(p.name)}</b><span>${esc(p.club||'Club TBA')}</span><p>${esc(p.playerId||'')} • ${esc(p.competition||'')} • ${esc(state.season?.name||DEFAULT_SEASON)}</p></div><button class="mini-btn danger" onclick="deleteMember('${p.id}')">Remove Member</button></article>`).join('')||'<p class="muted">No registered members.</p>'}</div>`;}
window.deleteMember=async id=>{const p=state.players.find(x=>x.id===id);if(!p)return;if(!confirm(`Remove ${p.name} from ${state.season?.name||DEFAULT_SEASON}? This deletes the registration.`))return;try{await adminDelete('players',id);alert('Member removed.');adminTab('members');}catch(e){console.error(e);alert('Could not remove member. Check Firestore Rules for admin writes.');}};
window.deleteNews=id=>adminDelete('news',id);
function adminHall(c){c.innerHTML=`<div class="admin-heading"><div><p class="eyebrow">LEGACY</p><h2>Hall of Fame</h2><p>Record champions by competition and Season.</p></div></div><div class="admin-form"><input id="hallSeason" value="${esc(state.season?.name||DEFAULT_SEASON)}" placeholder="Season"><select id="hallComp"><option>Premier League</option><option>Championship</option><option>UCL</option></select><input id="hallWinner" placeholder="Champion / Team"><input id="hallDate" type="date"><button class="primary" id="saveHall">Add Champion</button></div><div class="admin-list">${state.hall.map(h=>`<article class="admin-item"><b>🏆 ${esc(h.winner||h.team)}</b><span>${esc(h.season||'Season')} • ${esc(h.competition||'')}</span></article>`).join('')}</div>`;$('saveHall').onclick=async()=>{await adminSave('hallOfFame',null,{season:$('hallSeason').value.trim(),competition:$('hallComp').value,winner:$('hallWinner').value.trim(),date:$('hallDate').value,seasonId:SEASON_ID});adminTab('hall');};}
function adminSeason(c){const s=state.season||{};c.innerHTML=`<div class="admin-heading"><div><p class="eyebrow">SEASON MANAGEMENT</p><h2>Season settings</h2></div></div><div class="admin-form"><input id="seasonName" value="${esc(s.name||DEFAULT_SEASON)}" placeholder="Season name"><select id="seasonStatus"><option ${s.status==='Upcoming'?'selected':''}>Upcoming</option><option ${s.status==='Ongoing'?'selected':''}>Ongoing</option><option ${s.status==='Completed'?'selected':''}>Completed</option></select><input id="seasonYear" value="${esc(s.year||'2026')}" placeholder="Year"><button class="primary" id="saveSeason">Save Season</button></div>`;$('saveSeason').onclick=async()=>{const active=state.season?.activeCompetitions||ALL_COMPETITIONS;await adminSave('seasons',SEASON_ID,{name:$('seasonName').value.trim(),status:$('seasonStatus').value,year:$('seasonYear').value,current:true,activeCompetitions:active});adminTab('season');};}
auth.onAuthStateChanged(async u=>{state.admin=!!u&&!u.isAnonymous;await loadData();});

window.editFixture=async id=>{const f=state.fixtures.find(x=>x.id===id);if(!f)return;const h=prompt('Home team',f.homeTeam||f.home||'');if(h===null)return;const a=prompt('Away team',f.awayTeam||f.away||'');if(a===null)return;const d=prompt('Date (YYYY-MM-DD)',f.date||'');if(d===null)return;const r=prompt('Round / Match',f.round||'Match');if(r===null)return;try{await adminSave('fixtures',id,{homeTeam:h.trim(),awayTeam:a.trim(),date:d.trim(),round:r.trim()||'Match'});alert('Fixture updated.');adminTab('fixtures');}catch(e){console.error(e);alert('Could not update fixture.');}};
window.deleteFixture=async id=>{if(!confirm('Delete this fixture?'))return;try{await adminDelete('fixtures',id);alert('Fixture deleted.');adminTab('fixtures');}catch(e){console.error(e);alert('Could not delete fixture.');}};
